// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeHzYS7wJ0cA50uBZkfhnDhtP660yZ_Y8',
    appId: '1:521622314452:web:0b685923d14f31d4940a41',
    messagingSenderId: '521622314452',
    projectId: 'quizzo-1e009',
    authDomain: 'quizzo-1e009.firebaseapp.com',
    storageBucket: 'quizzo-1e009.firebasestorage.app',
    measurementId: 'G-WF2BPJWVJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdrAVvmVigAPwGz9g27nqAwLxvruIjok',
    appId: '1:521622314452:android:2067ec4f5d7ecca8940a41',
    messagingSenderId: '521622314452',
    projectId: 'quizzo-1e009',
    storageBucket: 'quizzo-1e009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFu91pU12l4s44bUwVOiLzcgqlB3N-6qw',
    appId: '1:521622314452:ios:8d11872bc31cec60940a41',
    messagingSenderId: '521622314452',
    projectId: 'quizzo-1e009',
    storageBucket: 'quizzo-1e009.firebasestorage.app',
    iosBundleId: 'com.example.quizzo',
  );
}
